name       : perl-file-listing
version    : '6.16'
release    : 8
source     :
    - https://cpan.metacpan.org/authors/id/P/PL/PLICEASE/File-Listing-6.16.tar.gz : 189b3a13fc0a1ba412b9d9ec5901e9e5e444cc746b9f0156d4399370d33655c6
homepage   : https://metacpan.org/pod/File::Listing
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : File::Listing - Parse directory listing
description: |
    This module exports a single function called parse_dir(), which can be used to parse directory listings.
rundeps    :
    - perl-http-date
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
