name       : perl-file-listing
version    : 6.04
release    : 4
source     :
    - https://cpan.metacpan.org/authors/id/G/GA/GAAS/File-Listing-6.04.tar.gz : 1e0050fcd6789a2179ec0db282bf1e90fb92be35d1171588bd9c47d52d959cf5
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : File::Listing - parse directory listing
description: |
    This module exports a single function called parse_dir(), which can be used to parse directory listings.
rundeps    :
    - perl-http-date
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
